; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.15
	robtillaart/TCA9555@^0.4.4
	earlephilhower/ESP8266Audio@^1.9.7
lib_ignore = ESP32-A2DP
; build_unflags = -DCONFIG_BT_NIMBLE_ENABLED
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
;	-DCONFIG_BT_ENABLED=1
;	-DCONFIG_BT_BLUEDROID_ENABLED=1
;	-DCONFIG_BT_CLASSIC_ENABLED=1
;	-DCONFIG_BT_SPP_ENABLED=1
;	-DBLUEDROID_ENABLED=1
;	-DCONFIG_BT_NIMBLE_ENABLED=0
;	-DCONFIG_BTDM_CTRL_MODE_BLE_ONLY=0
;	-DCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=1
;	-DCONFIG_BTDM_CTRL_MODE_BTDM=1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
; board_build.bluetooth = classic ; Not supported on S3
; board_build.extra_flags removed, merged into build_flags logic above if needed.

upload_speed = 921600
monitor_speed = 115200
extra_scripts = pre:kill_minicom.py
